### PR TITLE
Remove base_style and base_template relationship

### PR DESCRIPTION
**Pull request by 3j14**
As previously discussed, this will remove the field `base_style_id` from the `doku_template` model and subsequently remove all references and relationships associated with base Templates and base Stylesheets.

Along the way, I introduced ESLint which should help us detect issues earlier and enforce some JavaScript coding style guides. Appropriate commands can be found in the `package.json` file:

 - `npm run lint`
 - `npm run lint.fix` to automatically fix issues (if possible). Always check the result before committing!

While enforcing the ESLint rules, I stumbled upon some issues that have been fixed right-away. E.g. this:
https://github.com/desklab/doku/blob/b892d82978d88b081fb661a35d0f9f4a1e8bc727/doku/static/src/sites/templates.vue#L60

### CODE REVIEW

**Comment by ax-sc** [comment]
Did you notice the failing tests, @jnsdrtlf ? Seems like collecting them fails due to `name 'SQLAlchemySchema' is not defined` (this effects all seven tests)

In b08e86f68bd8d65399b988b09e79ef11de70ea31 `from marshmallow_sqlalchemy import SQLAlchemySchema` was removed from _doku/models/schemas/common.py_, could this be the reason for the failing tests?

**Comment by 3j14** [comment]
Oh no, I somehow missed that. Could you fix it for me please?

**Comment by ax-sc** [comment]
Fixed the failing tests in 2e614957db65e60f42d8cb1a2f6adc9e7f4d6e2b. I think we still have some problems with legacy base-stylesheets:

Removing a stylesheet (which was created as a base-stylesheet for a template when they still existed), which is no longer used by any template (and the correct tag _unused_ is shown as well), fails with:

```
psycopg2.errors.ForeignKeyViolation: update or delete on table "doku_stylesheet" violates foreign key constraint "doku_template_base_style_id_fkey" on table "doku_template"
DETAIL:  Key (id)=(1) is still referenced from table "doku_template".
```

**Comment by 3j14** [comment]
I am quite certain that you forgot to run `alembic upgrade head` ;)

The constraint should have been dropped in this line:
https://github.com/desklab/doku/blob/2e614957db65e60f42d8cb1a2f6adc9e7f4d6e2b/alembic/versions/c2d7aa36d0e7_remove_base_style.py#L21

**Review by 3j14 — COMMENTED** [review]
Thanks, that should be it 👍

**Comment by ax-sc** [comment]
As we dicussed / i showed you before, i did run `alembic upgrade head` and still got the error with my local development setting used for some time before. However, this seems to be related with some local issues with the state of the db and alembic. Conesquently i created a new doku environment from bottom up and the issue was no longer present, therefore i think we should merge this one, thanks for the work (also regarding the code clean-up)!

**Review by ax-sc — APPROVED** [review]

**Pull request merged**
